### PR TITLE
WIP: Helm refactor

### PR DESCRIPTION
**Pull request by etsauer**
## Linked Issues?

resolves #<issue number> <-- Use this if merging should auto-close an issue

related to #<issue number> <-- Use this if it shouldn't

## Testing Instructions

Please include any additional commands or pointers in addition to our [standard PR testing process](/docs/Development.md#testing-pull-requests).

@redhat-cop/mdt

### CODE REVIEW

**Comment by themoosman** [comment]
I keep getting `Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "OperatorGroup" in version "operators.coreos.com/v1alpha1` when running the first command.

**Comment by etsauer** [comment]
@themoosman what version of openshift?

**Comment by themoosman** [comment]
4.5.4.  If I change the apiVersion to `apiVersion: 'operators.coreos.com/v1' in the operatorgroup.yaml I get around that issue.  
`

**Comment by etsauer** [comment]
@themoosman updated.

**Comment by themoosman** [comment]
Now there seems to be an issue with the approver job.  
```
kmoos 🎩︎Downloads]$ oc get jobs
NAME                   COMPLETIONS   DURATION   AGE
installplan-approver   0/1           2m28s      2m28s

[kmoos 🎩︎Downloads]$ oc get pods
NAME                         READY   STATUS    RESTARTS   AGE
installplan-approver-nmrnb   1/1     Running   0          2m33s

[kmoos 🎩︎Downloads]$ oc logs installplan-approver-nmrnb 
Approving operator Install096096
Plans.  Waiting a few seconds to make sure the InstallPlan gets created first.
```

**Comment by etsauer** [comment]
So is the job hung?

**Comment by themoosman** [comment]
You can see the (only) message in the log "Approving operator Install096096 Plans.  Waiting a few seconds to make sure the InstallPlan gets created first."

Deleting the pod, resulted in the same thing.

**Comment by themoosman** [comment]
I added some debug lines and it seems to hang on this line `until [ "$(oc get installplan --template="{{ "{{" }} range \$item := .items {{ "}}{{" }} range \$item.spec.clusterServiceVersionNames {{ "}}{{" }} if eq . \"$desiredcsv\" {{ "}}{{" }} printf \"%s\n\" \$item.metadata.name {{ "}}{{end}}{{end}}{{end}}" }}")" != "" ]; do sleep 2; done` while processing the grafana sub.

**Pull request merged**
