### PR TITLE
Added conftest tests to resources

### PR DESCRIPTION
**Pull request by garethahealy**
## Describe the behavior changes introduced in this PR

Addes conftest action and tests. 

## Linked Issues?

resolves https://github.com/redhat-cop/pelorus/issues/148

## Testing Instructions

See action or `bats _test/conftest.sh`

@redhat-cop/mdt

### CODE REVIEW

**Comment by garethahealy** [comment]
Ready for review. The CI currently fails due to: https://github.com/redhat-cop/pelorus/issues/150

**Comment by etsauer** [comment]
@garethahealy are there checks in here for the presence of `.metadata.namespace`? That should be flagging a few files currently.

**Comment by garethahealy** [comment]
@etsauer ; no, only doing these currently:
- https://github.com/redhat-cop/rego-policies/tree/master/policy/ocp/deprecated

**Comment by etsauer** [comment]
@garethahealy ok, cool. Understood. Could you add a readme describing 1. how to run tests locally, and 2. how to enable new policies?

**Comment by garethahealy** [comment]
@etsauer ; pushed `TESTING.md` - that explain everything you want?

**Pull request merged**
